# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        custom_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            provider: custom_provider
#            form_login:
#                login_path: loginAction
#                check_path: checkAction
#                csrf_provider: security.csrf.token_manager
#                default_target_path: userRedirectAction
            logout:
                path: /logout
                target: /

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~
